In [22]:
import importlib
import pandas as pd
from io import StringIO

In [4]:
import Scrape_pokemon_functions as sp
importlib.reload(sp)
import Scrape_pokemon_functions as sp

### Trying to fix the broken decklists

In [8]:
df = pd.read_csv('Data_Files/dropdown_df.csv')

In [35]:
lst = df[df['Deck'].str.contains('Alolan Raichu ex')]['Decklists'].reset_index(drop=True)[0]

In [27]:
pd.read_json(StringIO(lst))

    Amount                   Card   Version
0        2                Pikachu   (A1-94)
1        2          Alolan Raichu        NA
2        2              Pachirisu  (A2b-25)
3        2               Oricorio   (A3-66)
4        1                Shaymin  (A2a-69)
5        2   Professor's Research        NA
6        1                  Guzma        NA
7        1                  Cyrus        NA
8        1                Sabrina        NA
9        1         Pokémon Center        NA
10       2              Poké Ball        NA
11       1  Pokémon Communication        NA
12       1           Rocky Helmet        NA
13       1             Giant Cape        NA

### This is a problem since I already scraped all the decklists and it took forever
### sadly I'm going to have to do it again

In [86]:
df1 = pd.read_csv('Data_Files/A3_all_2s.csv')

In [87]:
df1[df1['Decklists'].str.contains('Jang')]['Decklists'].reset_index(drop=True)[0]

'{"Amount":{"0":"2","1":"1","2":"2","3":"2","4":"2","5":"2","6":"1","7":"1","8":"1","9":"2","10":"2","11":"2"},"Card":{"0":"Jangmo","1":"Hakamo","2":"Kommo","3":"Oricorio","4":"Professor\'s Research","5":"Pok\\u00e9mon Center","6":"Cyrus","7":"Celestic Town","8":"Lillie","9":"Rare Candy","10":"Pok\\u00e9 Ball","11":"Giant Cape"},"Version":{"0":"NA","1":"NA","2":"NA","3":"(A3-66)","4":"NA","5":"NA","6":"NA","7":"NA","8":"NA","9":"NA","10":"NA","11":"NA"}}'

In [67]:
pd.read_json(StringIO(x))

    Amount                  Card   Version
0        2               Flabébé  (A1a-36)
1        2               Floette  (A1a-37)
2        2               Florges  (A1a-38)
3        2                 Ralts  (A1-130)
4        2                Kirlia  (A1-131)
5        2             Gardevoir  (A1-132)
6        2                Mew ex  (A1a-32)
7        2  Professor's Research        NA
8        1  Budding Expeditioner        NA
9        2             Poké Ball        NA
10       1         Mythical Slab        NA

### This notebook was just used to gather info on how to construct the regex better